landiary/diary/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('mydiary/', views.mydiary, name= 'mydiary'),
    path('setting/', views.setting),
    path('writediary/', views.write_diary, name= 'writediary'),
    path('pickdiary/', views.pick_diary),
    path('groupdiary/<str:group>', views.group_diary, name="groupdiary"),
    path('makegroup/', views.make_group),
    path('makegroup/making', views.making_group),
    path('search/', views.search_group),
    path('invite/check/<str:token>', views.invite_check),
    path('invite/join/group', views.join_group),
    path('pick', views.pick, name='pick'),
    path('remove', views.remove),
    path('comment_delete', views.comment_delete),
    path('pickdiary_comment_delete', views.pickdiary_comment_delete),
    path('calendardiary_comment_delete', views.calendardiary_comment_delete),
    path('mydiary_delete',views.mydiary_delete),
    path('calendardiary/', views.calendar_diary, name='calendardiary'),
    path('calendardiary_delete',views.calendardiary_delete),
    path('comment_delete_2', views.comment_delete_2),
    # path('my_diary/', views.ViewMydiary.as_view(), name='ViewMydiary'),
    # path('write_diary/', views.write_diary, name='WriteDiary'),
    # path('edit_diary/<int:id>/', views.edit_diary, name='EditDiary'),
    path('<int:pk>/editdiary',views.edit_diary, name = 'editdiary'),
    path('write_comment',views.write_comment),
    path('edit_comment',views.edit_comment)
]

landiary/landiary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('login.urls')),
    path('main/', include('diary.urls')),
    # path(,include('diary.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns = urlpatterns+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

landiary/diary/models.py
import datetime
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils import timezone


class Category(models.Model):
    C_name = models.CharField(max_length=100)
    C_detail = models.CharField(max_length=1000)
    visible = models.IntegerField(default=1)
    anonymous = models.IntegerField(default=0)
    link = models.CharField(max_length=1000, default="http://localhost:8000/main/groupdiary/all")
    def __str__(self):
        return "%s" % (self.C_name)

from login.models import User

class Post(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='../media/',blank=True, null=True)
    content = models.CharField(max_length=4000)
    published = models.DateTimeField(auto_now=True)
    weather = models.CharField(max_length=15)
    emotion = models.CharField(max_length=15)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    timeout = models.IntegerField(default=0)

    def __str__(self):
        return "%s - %s" % (self.username, self.title)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    created = models.DateTimeField(auto_now=True)
    def __str__(self):
        return "%s 의 댓글" % (self.post)

class PickPost(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    pick_posts = models.ManyToManyField(Post, blank=True)
    def __str__(self):
        return "%s의 뜯어온일기" % (self.username)

landiary/login/models.py
from diary.models import Category
from django.db import models


# Create your models here.
class User(models.Model):
    nick_name = models.CharField(max_length=40)
    email = models.CharField(max_length=100,null=True,blank=True)
    categories = models.ManyToManyField(Category, blank=True)
    def __str__(self):
        return "%s" % (self.nick_name)

landiary/diary/forms.py
from django.forms import ModelForm
from .models import Category, Post

class MakeGroupFrom(ModelForm):
    class Meta:
        model = Category
        fields = ('C_name', 'C_detail', 'visible', 'anonymous')

class PostForm(ModelForm):
	class Meta:
		model = Post
		fields = ('title','photo','content','weather','emotion',)

landiary/diary/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.utils import timezone
from django.views.decorators.http import require_http_methods
from django.views import generic

from .models import Post, Category, Comment, PickPost
from login.models import User
from datetime import date

from .forms import MakeGroupFrom, PostForm
from raven.contrib.django.raven_compat.models import client


import jwt # for token generation
from datetime import date #현재날짜 받아오기
import datetime
#from django.core.files.uploadhandler import FileUploadHandler

  
def main(request):
  try: # 로그인했을때만 접근가능하도록 처리
    user = request.session['user_name']
  except:
    return redirect('../unloginpage')
  # user = "user2"
  user_id = User.objects.get(nick_name = user).id
  user_posts = Post.objects.filter(username = user_id)
  user_today_posts = user_posts.filter(published__date = date.today())
  user_otherday_posts = user_posts.exclude(published__date = date.today())

  item = {
    'today_posts' : user_today_posts,
    'otherday_posts' : user_otherday_posts,
    'user' : user
  }

  # login message를 위한 로직
  try:
    message = request.session['login_message']
    del request.session['login_message']
    item['message'] = message
  except:
    pass
  try:
    message = request.session['logout_message']
    del request.session['logout_message']
    item['message'] = message
  except:
    pass
  return render(request, 'diary/main.html', item)

# 내 일기장에 일기들을 불러와주는 함수
def mydiary(request):
  try: # 로그인했을때만 접근가능하도록 처리
    user = request.session['user_name']
  except:
    return redirect('../../unloginpage')
  user_id = User.objects.get(nick_name = user).id
  user_posts = Post.objects.filter(username = user_id)
  user_posts_idlist = []
  for post in user_posts:
    user_posts_idlist.append(post.id)

  comments = {}
  for post in user_posts:
    comments[post.id] = []
    tmp_comments = Comment.objects.filter(post=post)
    comments[post.id].append(tmp_comments)
  user_posts_idlist.reverse()
  return render(request, 'diary/my_diary_view.html', {'posts':user_posts, 'comments':comments, 'posts_idlist':user_posts_idlist})

def mydiary_delete(request):
  try:
    user = request.session['user_name']
  except:
    return redirect('../../unloginpage')
  user_id = User.objects.get(nick_name = user).id
  post_id = request.POST['post_id']
  user = User.objects.get(id = user_id)
  user_post = Post.objects.filter(username = user)
  selected_user_post = user_post.get(id = post_id)
  selected_user_post.delete()
  return redirect('../main/mydiary/')

def setting(request):
  try: # 로그인했을때만 접근가능하도록 처리
    user = request.session['user_name']
  except:
    return redirect('../../unloginpage')
  user = User.objects.get(nick_name = user)
  categories = user.categories.all()
  return render(request, 'diary/setting.html',{'user':user,'categories':categories})

def edit_diary(request, pk):
  try:
    user = request.session['user_name']
  except:
    return redirect('../../unloginpage')
  
  post = get_object_or_404(Post, pk=pk)
  #user_id = User.objects.get(nick_name = user).id
  if request.method == "POST":
    original_post = Post.objects.get(id = request.POST['post_id'])
    if original_post.username != User.objects.get(nick_name = user):
      redirect('../../errorpage')
    original_post.title = request.POST['title']
    # original_post.category = Category.objects.get(C_name = request.POST['category'])
    original_post.emotion = request.POST['emotion']
    original_post.weather = request.POST['weather']
    if request.FILES['photo'] == "": # 사진을 수정하지 않으면 걍 내비둔다
      pass
    else: # 새로운 사진을 첨부했으면, 기존의 사진을 지우고 새로 첨부한 사진을 db에 입력
      original_post.photo.delete(save=False)
      original_post.photo = request.FILES['photo'] 
    original_post.content = request.POST['content']
    original_post.save()
    return redirect('../mydiary')

  else:
    form = PostForm(instance=post)
    #redirect('../../errorpage')
  return render(request, 'diary/edit_diary.html',{'form':form, 'post':post})

def write_diary(request):
  try: # 로그인했을때만 접근가능하도록 처리
    user = request.session['user_name']
  except:
    return redirect('../../unloginpage')
  if request.method == "POST":
    user_id = User.objects.get(nick_name = user).id
    if request.POST['category'] == '':
      category_id = 0
    else:
      category_id =  Category.objects.get(C_name = request.POST['category']).id
    #try:
     # category_id = Category.objects.get(C_name = request.POST['category']).id
    #except:
     # category_id = 0
    try:
        form = PostForm(request.POST,request.FILES)
    except:
        client.captureException()
    if form.is_valid():
      post = form.save(commit=False)
      post.username = User.objects.get(id = user_id)
      #post.photo = request.FILES # 해당 부분 주석처리하면 오류 발생 안함
      if category_id == 0:
        pass
      else:
        post.category = Category.objects.get(id = category_id )
      post.save()
      return redirect('../mydiary')
  else:
    form = PostForm()
    user = User.objects.get(nick_name = user)
    item = {
      'user_categories' : user.categories.all()
    }
  return render(request, 'diary/write_diary.html', item)

def pick(request):
  try: # 로그인했을때만 접근가능하도록 처리
    user = request.session['user_name']
  except:
    return redirect('../../unloginpage')
  if request.method == "GET":
    return redirect('../../errorpage')
  user_id = User.objects.get(nick_name = user).id
  post_id = request.POST['post_id']
  user = User.objects.get(id = user_id)
  pick_post = Post.objects.get(id = post_id)
  try:
    PickPost_obejct = PickPost.objects.get(username = user)
    PickPost_obejct.pick_posts.add(pick_post)
  except: 
    PickPost_obejct = PickPost.objects.create(username = user)
    PickPost_obejct.pick_posts.add(pick_post)
    PickPost_obejct.save()
  return redirect('../main/groupdiary/all')

def pick_diary(request):
  try: # 로그인했을때만 접근가능하도록 처리
    user = request.session['user_name']
  except:
    return redirect('../../unloginpage')
  # user = "test_user1"
  user_id = User.objects.get(nick_name = user).id
  try:
    user_posts = PickPost.objects.get(username = user_id).pick_posts.all()
  except:
    user_posts=[]
  
  user_pickposts_idlist = []
  for post in user_posts:
    user_pickposts_idlist.append(post.id)
  user_pickposts_idlist.reverse()
  comments = {}
  for post in user_posts:
    comments[post.id] = []
    tmp_comments = Comment.objects.filter(post=post)
    comments[post.id].append(tmp_comments)
  item = {
    'pickposts' : user_posts,
    'comments' : comments,
    'pickposts_idlist' : user_pickposts_idlist
  }
  return render(request, 'diary/pick_diary_view.html', item)
  
def remove(request):
  try: # 로그인했을때만 접근가능하도록 처리
    user = request.session['user_name']
  except:
    return redirect('../../unloginpage')
  user_id = User.objects.get(nick_name = user).id
  post_id = request.POST['remove_id']
  # user = PickPost.objects.get(id = user_id)
  post = Post.objects.get(id = post_id)
  user_pickposts = PickPost.objects.get(username = user_id).pick_posts
  user_pickposts.remove(post)
  return redirect('../main/pickdiary/')

def comment_delete(request):
  try: # 로그인했을때만 접근가능하도록 처리
    user = request.session['user_name']
  except:
    return redirect('../../unloginpage')
  user_id = User.objects.get(nick_name = user).id
  post_id = request.POST['comment_id']
  user_comment = Comment.objects.filter(author = user_id)
  try:
    selected_user_comment = user_comment.get(id = post_id)
    selected_user_comment.delete()
  except:
    return redirect('../errorpage')
  return redirect('../main/groupdiary/all')
  
def comment_delete_2(request):
  try: # 로그인했을때만 접근가능하도록 처리
    user = request.session['user_name']
  except:
    return redirect('../../unloginpage')
  user_id = User.objects.get(nick_name = user).id
  post_id = request.POST['comment_id']
  user_comment = Comment.objects.filter(author = user_id)
  try:
    selected_user_comment = user_comment.get(id = post_id)
    selected_user_comment.delete()
  except:
    return redirect('../errorpage')
  selected_group = request.POST['selected_group']
  return redirect('../main/groupdiary/'+selected_group)

def pickdiary_comment_delete(request):
  try: # 로그인했을때만 접근가능하도록 처리
    user = request.session['user_name']
  except:
    return redirect('../../unloginpage')
  user_id = User.objects.get(nick_name = user).id
  post_id = request.POST['comment_id']
  user_comment = Comment.objects.filter(author = user_id)
  try:
    selected_user_comment = user_comment.get(id = post_id)
    select_uset_comment.delete()
  except:
    return redirect('../errorpage')
  return redirect('../main/pickdiary')



def group_diary(request,group="all"):
  try: # 로그인했을때만 접근가능하도록 처리
    user = request.session['user_name']
  except:
    return redirect('../../unloginpage')
  # 현재 유저 이름에 대한 db의 id를 가져와야함. 예시를 바탕으로, test_user1의 id는 1임
  user_id = User.objects.get(nick_name = user).id
  all_posts = Post.objects.all()
  user_posts = []
  # filter 를 통해서 어떤 유저 아이디에 해당하는 post들을 다 가져와서 user_posts 에 저장한다. 외래키 이기 때문에 username으로 해도 id로 탐색.
  user_categories = User.objects.filter(id = user_id)[0].categories.all()
  for post in all_posts:
    for category in user_categories:
      if post.category == category:
        user_posts.append(post)
  # 해당하는 id 에 맞는 유저를 찾아서 [0]을 붙인 이유가 뭐지 그리고 모든 categories를 변수에 저장한다.
  # 전체보기를 위해  user_categories_namelist의 맨 앞에 'all' 값을 하나 추가한다.
  user_categories_namelist = ["all"]
  for category in user_categories: # user_categories 안에 있는 카테고리들을 반복한다.
    user_categories_namelist.append(category.C_name) # 각 카테고리의 이름들을 namelist 변수에 담아준더ㅏ,
  user_categories_idlist = [] # 카테고리의 id 리스트와
  user_posts_idlist = [] # post의 id 리스트를 만들어주고
  for post in user_posts: # 특정 유저의 모든 post를 돌면서 
    user_posts_idlist.append(post.id) # 그 아이디 값을 변수에 담아준다.
    category = Category.objects.filter(C_name = post.category) # post의 카테고리가 원하는 카테고리의 이름과 같은 것들만 category 변수에 넣는다.
    if(len(category) == 0): # categorty 변수에 아무것도 없으면 

landiary/diary/templates/diary/calendar_click_mydiary_view.html
{% extends "diary/layout.html" %}
{% load static %}
{% block title %} Calendar_Diary {% endblock %}
{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
		$(document).ready(function() {
			$(".content_input").show(); //페이지를 로드할 때 표시할 요소
			$(".view_comment_icon").show();
			$(".mydiary_comment").hide(); //페이지를 로드할 때 숨길 요소
			$(".view_diary_icon").hide();
			$(".view_comment_icon").click(function(){
				$ (".view_comment_icon").hide();
				$ (".content_input").hide(); //클릭 시 첫 번째 요소 숨김
				$ (".view_diary_icon").show();
				$ (".mydiary_comment").show(); //클릭 시 두 번째 요소 표시
			return false;
			});
			$(".view_diary_icon").click(function(){
				$ (".view_diary_icon").hide();
				$ (".mydiary_comment").hide(); //클릭 시 첫 번째 요소 숨김
				$ (".view_comment_icon").show();
				$ (".content_input").show(); //클릭 시 두 번째 요소 표시
			return false;
			});
		});
</script>
<script type="text/javascript">
	$(function(){
	  var hover1 = $('.hover1');
	  var hover2 = $('.hover2');
	  var hover3 = $('.hover3');
	  var hover4 = $('.hover4');
	  var hover_comment_edit = $('.hover_comment_edit');
	  hover1.hover(function(){
	    hover1.css('font-size','30px');
	    hover1.css('color','#B90000');
	  },function(){
	    hover1.css('font-size','25px');
	    hover1.css('color','black');
	  });
	  hover2.hover(function(){
	    hover2.css('font-size','30px');
	    hover2.css('color','#B90000');
	  },function(){
	    hover2.css('font-size','25px');
	    hover2.css('color','black');
	  });
	  hover3.hover(function(){
	    hover3.css('font-size','30px');
	    hover3.css('color','#B90000');
	  },function(){
	    hover3.css('font-size','25px');
	    hover3.css('color','black');
	  });
	  hover4.hover(function(){
	    hover4.css('font-size','30px');
	    hover4.css('color','#B90000');
	  },function(){
	    hover4.css('font-size','25px');
	    hover4.css('color','black');
	  });
	});
</script>
{% endblock %}
<body class="main_footer_wrap">
							{% block highlight %}
							<span class="mydiary_write"><a href="../writediary">일기 쓰기</a></span>
							<span class="mydiary_mydiary menu_highlight">내 일기장</span>
							<span class="mydiary_pick"><a href="../pickdiary">뜯어온 일기장</a></span>
							<span class="mydiary_exchange"><a href="../groupdiary/all">교환 일기장</a></span>
							<span class="mydiary_setup"><a href="../setting">설정</a></span>
							<span class="mydiary_logout"><a href="../../logout">로그아웃</a></span>
							{% endblock %}

		
		{% block main %}
		<div class="main_footer_wrap" id="1">
			<main>
				<div class="calendar_click_mydiary_main_wrap">
					<div class="view_mydiary_wrap main_common">
						<div class="title_input clearfix">
							<div class="view_mydiary_title">
								{{ post.title }}
							</div>
							<div class="view_mydiary_category_wrap">
								<span>
									#내 일기장
								</span>
								<span class="my_diary_emotion_img">
									<img src="{% with 'img/'|add:post.emotion|add:'_color.png' as image_static %}{% static image_static %}{% endwith %}" alt="" width="25px" height="25px">
								</span>&nbsp;
								<span>
									<img src="{% with 'img/'|add:post.weather|add:'_color.png' as image_static %}{% static image_static %}{% endwith %}" alt="" width="25px" height="25px">
								</span>
							</div>
						</div>
						
						<div class="mydiary_date_input">
							<span>{{ post.published|date:"Y"}}년 </span>
							<span>{{ post.published|date:"m" }}월 </span>
							<span>{{ post.published|date:"d" }}일</span>
						</div>
						{% if post.photo %}
							<div class="image_input">
								<img class="diary_image" src= "{{ post.photo.url }}" />
							</div>
						{% endif %}
						<div class="view_mydiary_func">
							<span class="hover1">
								<i class="far fa-edit"></i>
								수정하기
							</span>
							<span class="view_comment_icon hover2">
								<i class="far fa-comment-alt"></i>
								댓글 보기
							</span>
							<span class="view_diary_icon hover3">
								<i class="far fa-eye"></i>
								일기 보기
							</span>
							<span class="hover4">
									<form name="myForm_mydiary_delete_{{post.id}}" method="POST" action="../calendardiary_delete">{% csrf_token %}
										<input type="hidden" name="post_id" value="{{ post.id }}" />
										<i class="fas fa-eraser"></i><a href="#" onclick="javascript:document.myForm_mydiary_delete_{{post.id}}.submit();">지우기</a>
									</form>
							</span>
						</div>
						<div class="content_input">
							<form id="paper" method="get" action="">
								<textarea placeholder="일기 내용" id="text" name="text" rows="4" style="overflow: hidden; word-wrap: break-word; resize: none; height: 400px; " disabled>{{post.content}}</textarea>  
								<br>
							</form>
						</div>
						<div class="comment_input_wrap">
							<table class="comment_table mydiary_comment">
								{% for key, value in comments.items %}
									{% if key == post.id %}
										{% for tmp_comments in value %}
											{% for comment in tmp_comments %}
								<tr class="row">
									<td class="diary_nickname">{{comment.author}}</td>
									<td class="comment_content">{{comment.content}}</td>
									<td class="view_diary_comment_func">
											<form method="POST" name="comment_{{comment.id}}_delete" action="../calendardiary_comment_delete">
												{% csrf_token %}
												<input type="hidden" name="post_id" value="{{ comment.post.id }}"/>
												<input type="hidden" name="comment_id" value="{{ comment.id }}"/>
											 <button class="view_diary_comment_func_button" onclick="javascript:document.comment_{{comment.id}}_delete.submit();">
												<img id="delete_img" width="13px" height="13px" src="{% static 'img/delete.png' %}" alt="삭제하기">
											 </button>
											 </form>
									</td>
								</tr>
											{% endfor %}
										{% endfor %}
									{% endif %}
								{% endfor %}
							</table>
						</div>
					</div>
				</div>
			</main>
		</div>
		{% endblock %}

landiary/diary/templates/diary/invite_check.html
{% load static %}
<!doctype html>
<html lang = "ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>LANDI LOGIN</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
	<div class="wrap">
		<header>
			<div class="header_background_wrap">
				<div class="new_header_wrap">
					<div class="new_logo">
                        <a href="http://localhost:8000/main">
                            LANDI
                        </a>
                    </div>
					<div class="blank_div"> </div>
				</div>
			</div>
		</header>
		<div class="main_footer_wrap">
			<div class="main_wrap">
				<div class="login_wrap">
					<div class="invite_background">      
                        <div class="invite_check_text">
                            안녕하세요. {{ user }}님!<br>
                            <span class="invite_group_name">{{ group }}</span> 교환일기장에 초대 받으셨어요 :)<br>
                            교환일기장에 참여하시겠어요?
                        </div><br>
                        <div class="invite_check_btn_group">
                            <div>
                                <form action="../join/group" name="answer" method="POST">{% csrf_token %}
                                    <input name="group" type="hidden" value="{{ group }}">
                                    <input name="user" type="hidden" value="{{ user }}">
                                    <input class="invite_check_btn_yes" name="answer" type="submit" value="네"/>
                                </form>
                            </div>  
                            <div>
                                <form action="../join/group" name="answer" method="POST">{% csrf_token %}
                                    <input class="invite_check_btn_no" name="answer" type="submit" value="아니요"/>
                                </form>
                            </div>
                        </div><br><br><br>
                        <div class="diary_submit_button_wrap">
                            <a href="../../" class="invite_toMain">main 으로 넘어가기</a>
                        </div>
					</div>
				</div>
			</div>
			<footer>
				<div class="footer_wrap">
					<div class="footer_icons clearfix">
						<br><br><br><br><br><br><br><br>
						<span class="footer_c">© 2018 LANDI</span>
						<br><br><br>
					</div>
				</div>
			</footer>
		</div>
	</div>
</body>

landiary/diary/templates/diary/layout.html
{% load static %}
<!doctype html>
<html lang = "ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">


</head>

{% block script %} {% endblock %}
    <div class="wrap">
        <header>
            <div class="header_background_wrap">
                <div class="new_header_wrap">
                    <div class="new_logo">
                        <a href="http://ec2-13-209-26-90.ap-northeast-2.compute.amazonaws.com/main">
                            LANDI
                        </a>
                    </div>
                    <div class="new_menu" style="float:right;">
                        <div class="new_menu_content">
                            {% block highlight %} {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </header>

            {% block main %} {% endblock %}

        <footer class="main_footer_wrap">
            <div class="footer_wrap">
                <div class="footer_icons clearfix">
                    <br><br><br><br><br>
                    <span class="footer_c">© 2018 LANDI</span>
                    <br><br><br>
                </div>
            </div>
        </footer>
    </div>
</body>

landiary/diary/templates/diary/shared_diary_search.html
{% extends "diary/layout.html" %}
{% load static %}
{% block title %} SearchGroup {% endblock %}
{% block script %}
<body>
{% endblock %}
							{% block highlight %}
							<span class="exchange_write"><a href="../writediray">일기 쓰기</a></span>
							<span class="exchange_mydiary"><a href="../mydiary">내 일기장</a></span>
							<span class="exchange_pick"><a href="../pickdiary">뜯어온 일기장</a></span>
							<span class="exchange_exchange menu_highlight">교환 일기장</span>
							<span class="exchange_setup"><a href="../setting">설정</a></span>
							<span class="exchange_logout"><a href="../../logout">로그아웃</a></span>
							{% endblock %}
		{% block main%}
		<div class="main_footer_wrap">
			<main>
				<div class="exdi_search_wrap">
					<div class="search_button">
						<form action="../search">
							교환 일기장 검색 : <input name="search" type="text" size="50" value="{{search_word}}" class="search_input">
							<input type="submit" class="exdi_diary_button" value="검색"/>
						</form>
						<br><br><span style="font-size: 20px">각 교환일기장을 눌러 일기를 열람하거나 참여하기를 눌러 함께 작성할 수 있어요 🤓</span>
					</div>

					{% for category in searched_categories %}

					<!-- 1개의 교환일기장 -->
					<div class="each_search_wrap">
						<a href="" style=""> <!-- 상자 클릭하면 exchange_diary_search_preview.html로 넘어감. -->
						<div class="search_left_wrap">
							<div class="diary_name_wrap">
								{{ category.C_name }}
							</div>
							<div class="diary_detail_wrap">
								{{ category.C_detail }}
							</div>
						</div>
						</a>
						<div class="search_right_wrap">
							<div> {{ category.user_set.count }} </div>
							<div>
								<!-- 참가하기 버튼은 get이 아닌 post요청으로 처리해야하므로 form태그를 생성, 전달하고자 하는 값을 input태그의 value에 넣어주면됨. 실제로 view에서는 아래의 a태그만 보이고, 해당 a태그를 누르면 form태그가 submit되도록 js를 구성함 -->
								<form name="enter_shared_diary_btn" action="" method="POST" >
									<input type="hidden" name="name1" value="value1">
								</form>	
								<a href="">
									<div class="search_enter_btn"onMouseOver="this.style.color='black'" onMouseout="this.style.color='white'" onClick="javascript:document.enter_shared_diary_btn.submit()">
										참여하기
									</div>
								</a>
							</div>
						</div>
					</div>
					
					{% endfor %}
					

				</div>
			</main>
			{% endblock %}

landiary/diary/templates/diary/unloginpage.html
{% load static %}
<html lang = "ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>404 ERROR</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
	<div class="main_404_wrap">
		<div class="text_404_wrap">
			<div class="text_404 error_404">ERROR ROUTE</div>
			<br>
			<div class="text_404">죄송합니다. 로그인을 하고 난 뒤에 이용할 수 있는 페이지입니다.</div>
			<div class="text_404">로그인을 먼저 해주세요.</div>
			<br>
			<a class="to_login" href="">로그인 하러가기</a>
		</div>
	</div>
</body>